### ISSUE TITLE
MAIN WIKI: Add information about no ICO / no IEO to TFT section

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/home#173]
We need to add some information about how we never had an ICO or IEO and why – and that TFT are only minted when capacity is added to the TF Grid.

Note: I do think we should include that we did explore these options but in the end we chose not to for XYZ reason.

Adding to 'Now' in case it can get done by Sunday but feel free to move to 'Next' as it is not urgent.

**Comment by Sacha96** [comment]
HEADLINE: NOT YOUR AVERAGE CRYPTO PROJECT
Headline left column - IF YOU ARE LOOKING FOR THESE THINGS, PLEASE MOVE ON
Headline right column - WE ARE P2P

We are not a blockchain -> But we are utilizing blockchain
No ICO or pump&dump -> But our token is from 2018
and a few more lines like this

**Comment by Sacha96** [comment]
ThreeFold: A different approach to Blockchain

ThreeFold had no ICO nor IEO. It pre-farmed it’s tokens.

ThreeFold didn’t have any ICO or IEO. ICOs and IEOs are fundraising schemes for blockchains to sell tokens to investors either directly (ICO) or through regulated exchanges (IEO). Instead, ThreeFold pre-farmed (ThreeFold’s sustainable alternative to mining) its tokens prior to going to the market.

This allowed ThreeFold to incentivise its early contributors, while also securing the ongoing development of the project until the launch of the Threefold Grid 2.0 in April 2020. Pre-mining is also an organic approach to the market, in line with ThreeFold’s values and vision of delivering products over using hype.

Product over Hype.

In some cases ICOs and IEOs were surrounded with hype. It is always very hard to judge the ability of a project to deliver it’s promises over a white paper.

Threefold therefore didn’ do an ICO or IEO. Instead of fundraising with a white paper, the technological development remained the primary focus. For 4 years, ThreeFold developed the whole technology stack, starting with an operating-system built from scratch to the autonomous smart contract and virtual system administrator technology that enables a fully autonomous Cloud.

In 2020, ThreeFold held its Token public launch on Liquid Exchange. At that time, the ThreeFold Grid was already live in it’s 2nd version.

Today, you can go through the whole Threefold Universe and find ready-to-use products. You can participate in growing the world’s most advanced peer-to-peer Internet infrastructure, or use the peer-to-peer compute and storage capacity available on the P2P Cloud.

ThreeFold is much more than a blockchain.

Threefold is not actually a blockchain project, rather it uses blockchain technology by combining it with other cutting-edge solutions. It is way more that just a blockchain alternative to a public cloud. ThreeFold started everything from scratch; built a super-lightweight and shell-less operating system, and a fully autonomous (self-driving and self-healing) architecture to enable a true peer-to-peer infrastructure with zero intermediaries that leads to high efficiency and minimum complexity.

The blockchain database (BCDB) acts a registry for the workloads on the Threefold Grid. Workloads can only be accessed and managed with the private key of the data owner. The BCDB can prove to any party that their workloads are executed exactly as intended and that their data is untouched.

In most distributed systems, data is stored multiple times to guarantee redundancy. This leads to a lot of unnecessary overhead and is also not the most secure mechanism. Threefold uses a dispersed storage algorithm to store the workloads on the ThreeFold Grid. The dispersed storage algorithm breaks data into shards and stores them on different nodes. This enables two things – first, performance efficiency (no need for consensus to run compute and storage) and second, energy efficiency (as there’s no more need for data duplication).

**Comment by Sacha96** [comment]
Title: ThreeFold: A different approach

link from: token pages on main.io + farming

link to https://github.com/threefoldfoundation/info_threefold/issues/13 from product over hype section.

**Comment by gmachtel** [comment]
Maybe add sthg like "we didn't want to create value out of thin air, by only creating tokens for capacity that is truly connected to the TFGrid, we wanted to stay loyal to our values. The value behind TFT lies in the commercial value of the ThreeFold grid and the hardware that is connected, creating TFTs out of nothing would have gone against that principle".

**Comment by Sacha96** [comment]
see https://github.com/threefoldfoundation/info_threefold/issues/42
