### ISSUE TITLE
https://explorer.grid.tf/ needs updates

### ISSUE THREAD

**Issue by maximilianrang** [threefoldfoundation/home#174]
- [ ] https://explorer.grid.tf/ is currently expressing a fixed token price at 10ct. I would propose to remove that.
- [ ] We need an owner for that website.
- [ ] Please check if the remaining information is correct.
- [ ] If you are not the right person that I tagged, feel free to remove yourself from the issue.

**Comment by Vilnite** [comment]
We have 2 domains both showing slightly different data:
- https://explorer.threefold.io
- https://explorer.grid.tf

I've been informed that https://explorer.threefold.io is latest and most relevant site so we've linked all web presence to this domain.
I suggest to remove or redirect https://explorer.grid.tf

**Comment by maximilianrang** [comment]
Voting for a redirect so we don't get 404 on existing links.

**Comment by LeeSmet** [comment]
The reason there are mutliple sites is as follows:

Originally, we had https://explorer.grid.tf (and https://explorer.testnet.grid.tf, https://explorer.devnet.grid.tf), which is the explorer server used by zero-os (and tools to deploy on zero-os). Because zero-os works on different networks, we have different explorers (one per network).

At some point in the past, Kristof decided that we should have an aggregated view, which could show all nodes from all networks, but also still show nodes per different network. This is https://explorer.threefold.io. Essentially, this is an aggregator which periodically pulls and caches data from the original explorers.

So considering the above, the original `grid.tf` domains must remain operational, because:
  - They are used by zero-os directly, replacing them would require a zero-os update, and require checks on every call to make sure the link is correct (aggregator might have slightly different paths)
  - There is only one aggregator, so if we roll out an update, it would be activated for all networks, which is exactly why we have a separate explorer instance per network. We need to have an environment where we can test before going to production
  - The aggregator caches info, meaning it is not realtime, which will lead to "weird" behavior in zos (workloads will take some time before being decomissioned, for example), which in turn also lead to a tougher time debugging issues.
  - Most importantly, the aggregator pulls all its data from the original explorers. If they are replaced with a redirect, the aggregator will essentially pull from itself, and get stuck in an infinite loop.
 
For the UI price elements: these are simply fetched from the explorer server, which uses them internally for calculation of the workload cost. It is possible to remove these from the UI itself, if that is desired, please open an issue on the explorer repo: https://github.com/threefoldtech/tfexplorer (for the explorer.grid.tf) or https://github.com/threefoldtech/nodes-explorer (for explorer.threefold.io).

**Comment by Vilnite** [comment]
Issues to remove TFT Price block created:
https://github.com/threefoldtech/nodes-explorer/issues/5
https://github.com/threefoldtech/tfexplorer/issues/303
